### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by james-still** [frk1/hazedumper-rs#2]
I used hazedumper **around a month ago** and it was able to gather the offsets with ease - using it now, it seems to be struggling to work completely.

```
00:39:29 [INFO] Opening target process: csgo.exe
00:39:29 [INFO] Starting signature scanning: 0 items
00:39:29 [INFO] Finished signature scanning: 0/0 items successful
00:39:29 [INFO] Starting netvar scanning: 0 items
```

**Comment by frk1** [comment]
The hazedumper is working fine. I guess you made an error in your `config.json`.
