### ISSUE TITLE
Default instead of Constructor

### ISSUE THREAD

**Issue by Proximyst** [frk1/hazedumper-rs#3]
When looking through the code, I spotted a trait called `Constructor` defining `new() -> Self`; this is precisely how `Default::default()` is defined, which also happens to be in the standard included `std::prelude` and as such can be implemented on any type. It is a standard to define this if you happen to need such a method.

**Comment by frk1** [comment]
You can not do this in rust because the types I need the constructor for are from different crates:

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src\memlib\module.rs:44:1
   |
44 | impl Default for MODULEENTRY32W {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl doesn't use types inside crate
   |
   = note: the impl does not reference only types defined in this crate
   = note: define and implement a trait or new type instead
```
