### ISSUE TITLE
Cant compile project

### ISSUE THREAD

**Issue by sur-ser** [frk1/hazedumper-rs#5]
**### hi, please help me, when i try to compile project i have get this error:**

`error: failed to run custom build command for `hazedumper v2.4.2 (C:\hazedumper-rs-master)`
process didn't exit successfully: `c:\hazedumper-rs-master\target\release\build\hazedumper-f097d289482b0784\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Не удается найти указанный файл." }', src\libcore\result.rs:997:5`

**### here is all output:**

`
c:\hazedumper-rs-master>cargo build --release
    Updating crates.io index
  Downloaded chrono v0.4.6
  Downloaded nom v4.2.3
  Downloaded serde v1.0.92
  Downloaded serde_json v1.0.39
  Downloaded simplelog v0.6.0
  Downloaded regex v1.1.7
  Downloaded failure v0.1.5
  Downloaded structopt-derive v0.2.16
  Downloaded serde_yaml v0.8.9
  Downloaded log v0.4.6
  Downloaded winres v0.1.10
  Downloaded winapi v0.3.7
  Downloaded serde_derive v1.0.92
  Downloaded num-integer v0.1.41
  Downloaded toml v0.5.1
  Downloaded time v0.1.42
  Downloaded backtrace v0.3.30
  Downloaded version_check v0.1.5
  Downloaded aho-corasick v0.7.3
  Downloaded utf8-ranges v1.0.3
  Downloaded itoa v0.4.4
  Downloaded linked-hash-map v0.5.2
  Downloaded yaml-rust v0.4.3
  Downloaded structopt v0.2.16
  Downloaded num-traits v0.2.8
  Downloaded quote v0.6.12
  Downloaded proc-macro2 v0.4.30
  Downloaded cfg-if v0.1.9
  Downloaded memchr v2.2.0
  Downloaded ryu v0.2.8
  Downloaded dtoa v0.4.4
  Downloaded failure_derive v0.1.5
  Downloaded syn v0.15.36
  Downloaded term v0.5.2
  Downloaded heck v0.3.1
  Downloaded autocfg v0.1.4
  Downloaded thread_local v0.3.6
  Downloaded synstructure v0.10.2
  Downloaded rustc-demangle v0.1.15
  Downloaded libc v0.2.58
  Downloaded regex-syntax v0.6.7
  Downloaded clap v2.33.0
  Downloaded unicode-xid v0.1.0
  Downloaded backtrace-sys v0.1.28
  Downloaded lazy_static v1.3.0
  Downloaded dirs v1.0.5
  Downloaded unicode-segmentation v1.3.0
  Downloaded byteorder v1.3.2
  Downloaded cc v1.0.37
  Downloaded bitflags v1.1.0
  Downloaded strsim v0.8.0
  Downloaded vec_map v0.8.1
  Downloaded ucd-util v0.1.3
  Downloaded atty v0.2.11
  Downloaded unicode-width v0.1.5
  Downloaded textwrap v0.11.0
   Compiling synstructure v0.10.2
   Compiling structopt-derive v0.2.16
   Compiling serde_derive v1.0.92
   Compiling hazedumper v2.4.2 (C:\hazedumper-rs-master)
error: failed to run custom build command for `hazedumper v2.4.2 (C:\hazedumper-rs-master)`
process didn't exit successfully: `c:\hazedumper-rs-master\target\release\build\hazedumper-f097d289482b0784\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Не удается найти указанный файл." }', src\libcore\result.rs:997:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libcore\panicking.rs:85
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure,i32>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:293
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libpanic_unwind\lib.rs:87
  16: std::panicking::try
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:272
  17: std::panic::catch_unwind
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panic.rs:388
  18: std::rt::lang_start_internal
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:48
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  22: BaseThreadInitThunk
  23: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by GH-Rake** [comment]
Compiles fine for me, random thought tho:  Doing anything on the C drive is a pain lately on Windows 10 because of permissions.

Не удается найти указанный файл = Cannot find the file specified.

Maybe this is because of C drive permissions

I would run:

rustup update
cargo update

Put the repo on a different drive or in your documents folder and try building it again

**Comment by frk1** [comment]
Project compiles fine on my machine and with github projects so you should check your setup.
